export const BLOOD_GROUPS = ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'];

export const INDIAN_CITIES = [
  "Agartala", "Agra", "Ahmedabad", "Aizawl", "Ajmer", "Alappuzha", "Aligarh",
  "Ambala", "Amravati", "Amritsar", "Anantnag", "Asansol", "Aurangabad",
  "Baharampur", "Bareilly", "Bathinda", "Belagavi", "Bellary", "Bengaluru",
  "Bhagalpur", "Bhavnagar", "Bhilai", "Bhilwara", "Bhopal", "Bhubaneswar",
  "Bikaner", "Bilaspur", "Bokaro",
  "Chandigarh", "Chennai", "Coimbatore", "Cuttack",
  "Daman", "Davanagere", "Dehradun", "Delhi", "Dhanbad", "Dharamshala",
  "Dibrugarh", "Dimapur", "Durgapur",
  "Erode",
  "Faridabad",
  "Gandhinagar", "Gangtok", "Gaya", "Ghaziabad", "Gorakhpur", "Guntur",
  "Gurugram", "Guwahati", "Gwalior",
  "Haldwani", "Haridwar", "Hisar", "Howrah", "Hubli", "Hyderabad",
  "Imphal", "Indore", "Itanagar",
  "Jabalpur", "Jaipur", "Jalandhar", "Jamnagar", "Jammu", "Jamshedpur",
  "Jodhpur",
  "Kannur", "Kanpur", "Kargil", "Karnal", "Karimnagar", "Kavaratti",
  "Khammam", "Kochi", "Kohima", "Kolhapur", "Kolkata", "Kollam", "Kota",
  "Kozhikode", "Kurnool",
  "Leh", "Lucknow", "Ludhiana",
  "Madurai", "Malda", "Mandi", "Mangaluru", "Margao", "Meerut", "Moradabad",
  "Mumbai", "Muzaffarpur", "Mysuru",
  "Nagpur", "Nashik", "Navi Mumbai", "Nizamabad", "Noida",
  "Panaji", "Panipat", "Patiala", "Patna", "Port Blair", "Prayagraj",
  "Puducherry", "Pune", "Puri",
  "Raipur", "Rajkot", "Ranchi", "Rishikesh", "Roorkee", "Rourkela",
  "Sagar", "Salem", "Sambalpur", "Shillong", "Shimla", "Silchar",
  "Siliguri", "Silvassa", "Solapur", "Srinagar", "Surat",
  "Thane", "Thrissur", "Thiruvananthapuram", "Tiruchirappalli",
  "Tirunelveli", "Tirupati",
  "Udaipur", "Ujjain",
  "Vadodara", "Varanasi", "Vasco da Gama", "Vellore", "Vijayawada",
  "Visakhapatnam",
  "Warangal",
];
